import type { ReportLanguage } from "./reporting";

const fr = {
  title: "Rapports & analyses",
  eyebrow: "Reporting Bluu3",
  intro:
    "Les mesures, les contrôles et les interventions réunis dans un rapport clair, pour chaque bassin et chaque mois.",
  month: "Période",
  pool: "Piscine",
  allPools: "Toutes les piscines",
  apply: "Afficher",
  pdf: "Exporter le PDF",
  csv: "Exporter le CSV",
  exporting: "Préparation du PDF…",
  demo: "Données de démonstration · mai 2026",
  demoNote:
    "Ces données illustrent le reporting et ne décrivent pas des piscines suivies en temps réel.",
  measurements: "Mesures",
  checks: "Contrôles",
  interventions: "Interventions",
  attention: "Bassins à vérifier",
  range: "Dans les plages de référence",
  completed: "Interventions réalisées",
  records: "relevés sur la période",
  assessed: "sur les mesures complètes",
  urgent: "urgentes",
  portfolio: "Vue par bassin",
  selectPool: "Voir le détail",
  stable: "Aucun écart relevé",
  review: "À vérifier",
  empty: "Sans données",
  waterAlerts: "mesures hors plage",
  checkAlerts: "contrôles à reprendre",
  incomplete: "relevés incomplets",
  noData:
    "Aucun relevé sur cette période. Choisissez un autre mois ou ajoutez de nouvelles mesures.",
  detail: "Détail du bassin",
  trends: "Évolution des mesures",
  ph: "pH",
  chlorine: "Chlore",
  temperature: "Température",
  date: "Date",
  reference:
    "Repères de suivi : pH 7,2–7,6 · chlore 1–3 mg/L. Ils ne constituent pas une certification de conformité.",
  eco: "Eco-Score estimé",
  ecoNote: "Estimation MVP calculée sur les données de la période.",
  noMeasurements: "Aucune mesure sur la période.",
  noChecks: "Aucun contrôle sur la période.",
  noInterventions: "Aucune intervention sur la période.",
  assistant: "Synthèse assistée",
  assistantIntro:
    "Une lecture rapide de la période et des actions à prioriser.",
  generate: "Générer la synthèse IA",
  generating: "Analyse de la période…",
  regenerate: "Actualiser la synthèse IA",
  automatic: "Synthèse automatique",
  ai: "Analyse IA · Hugging Face",
  highlights: "Points clés",
  recommendations: "Olivia AI recommande",
  fallback:
    "L’assistant IA est indisponible. La synthèse automatique reste utilisable.",
  notConfigured:
    "La synthèse IA sera disponible après configuration de l’assistant. La synthèse automatique et les exports sont déjà disponibles.",
  error: "La demande n’a pas abouti. Réessayez dans un instant.",
  rateLimited: "Trop de demandes rapprochées. Réessayez dans une minute.",
  generated: "Générée le",
  reviewNote:
    "Synthèse à relire par le pisciniste avant transmission au propriétaire.",
  loading: "Chargement…",
  scheduled: "Planifiée",
  done: "Réalisée",
  urgentStatus: "Urgente",
  type: "Type",
  status: "Statut",
  cover: "Couverture",
  filtration: "Filtration",
  safety: "Sécurité",
  cleanliness: "Propreté",
  passed: "OK",
  failed: "À reprendre",
  unknown: "Non renseigné",
  reportTitle: "Rapport mensuel piscine",
  period: "Période",
  automaticPdf: "Synthèse automatique basée sur les relevés",
  estimated: "estimé",
  noPools: "Aucune piscine disponible.",
};
type Copy = typeof fr;
export const reportCopy: Record<ReportLanguage, Copy> = {
  fr,
  en: {
    title: "Reports & insights",
    eyebrow: "Bluu3 reporting",
    intro:
      "Measurements, checks and interventions brought together in a clear report for every pool and every month.",
    month: "Period",
    pool: "Pool",
    allPools: "All pools",
    apply: "View",
    pdf: "Export PDF",
    csv: "Export CSV",
    exporting: "Preparing PDF…",
    demo: "Demo data · May 2026",
    demoNote:
      "These records illustrate reporting and do not describe pools monitored in real time.",
    measurements: "Measurements",
    checks: "Checks",
    interventions: "Interventions",
    attention: "Pools to review",
    range: "Within reference ranges",
    completed: "Completed interventions",
    records: "records in this period",
    assessed: "of complete measurements",
    urgent: "urgent",
    portfolio: "Pool overview",
    selectPool: "View details",
    stable: "No recorded deviation",
    review: "Review needed",
    empty: "No data",
    waterAlerts: "out-of-range measurements",
    checkAlerts: "checks to repeat",
    incomplete: "incomplete records",
    noData:
      "No records for this period. Choose another month or add new measurements.",
    detail: "Pool details",
    trends: "Measurement trends",
    ph: "pH",
    chlorine: "Chlorine",
    temperature: "Temperature",
    date: "Date",
    reference:
      "Monitoring references: pH 7.2–7.6 · chlorine 1–3 mg/L. These are not a compliance certification.",
    eco: "Estimated Eco-Score",
    ecoNote: "MVP estimate calculated using data from this period.",
    noMeasurements: "No measurements in this period.",
    noChecks: "No checks in this period.",
    noInterventions: "No interventions in this period.",
    assistant: "Assisted summary",
    assistantIntro:
      "A quick reading of the period and the actions to prioritize.",
    generate: "Generate AI summary",
    generating: "Analyzing this period…",
    regenerate: "Refresh AI summary",
    automatic: "Automatic summary",
    ai: "AI analysis · Hugging Face",
    highlights: "Key points",
    recommendations: "Olivia AI recommends",
    fallback:
      "The AI assistant is unavailable. The automatic summary remains available.",
    notConfigured:
      "The AI summary will be available once the assistant is configured. The automatic summary and exports are already available.",
    error: "The request failed. Try again shortly.",
    rateLimited: "Too many requests in a short period. Try again in a minute.",
    generated: "Generated on",
    reviewNote:
      "The pool professional should review this summary before sharing it with the owner.",
    loading: "Loading…",
    scheduled: "Scheduled",
    done: "Completed",
    urgentStatus: "Urgent",
    type: "Type",
    status: "Status",
    cover: "Cover",
    filtration: "Filtration",
    safety: "Safety",
    cleanliness: "Cleanliness",
    passed: "OK",
    failed: "Repeat check",
    unknown: "Not recorded",
    reportTitle: "Monthly pool report",
    period: "Period",
    automaticPdf: "Automatic summary based on recorded data",
    estimated: "estimated",
    noPools: "No pools available.",
  },
  es: {
    title: "Informes y análisis",
    eyebrow: "Informes Bluu3",
    intro:
      "Mediciones, controles e intervenciones reunidos en un informe claro para cada piscina y cada mes.",
    month: "Periodo",
    pool: "Piscina",
    allPools: "Todas las piscinas",
    apply: "Ver",
    pdf: "Exportar PDF",
    csv: "Exportar CSV",
    exporting: "Preparando PDF…",
    demo: "Datos de demostración · mayo de 2026",
    demoNote:
      "Estos datos ilustran los informes y no describen piscinas supervisadas en tiempo real.",
    measurements: "Mediciones",
    checks: "Controles",
    interventions: "Intervenciones",
    attention: "Piscinas por revisar",
    range: "Dentro de los rangos de referencia",
    completed: "Intervenciones realizadas",
    records: "registros en el periodo",
    assessed: "de las mediciones completas",
    urgent: "urgentes",
    portfolio: "Vista por piscina",
    selectPool: "Ver detalle",
    stable: "Sin desviaciones registradas",
    review: "Por revisar",
    empty: "Sin datos",
    waterAlerts: "mediciones fuera de rango",
    checkAlerts: "controles por repetir",
    incomplete: "registros incompletos",
    noData:
      "No hay registros para este periodo. Elige otro mes o añade nuevas mediciones.",
    detail: "Detalle de la piscina",
    trends: "Evolución de las mediciones",
    ph: "pH",
    chlorine: "Cloro",
    temperature: "Temperatura",
    date: "Fecha",
    reference:
      "Referencias de seguimiento: pH 7,2–7,6 · cloro 1–3 mg/L. No constituyen una certificación de conformidad.",
    eco: "Eco-Score estimado",
    ecoNote: "Estimación MVP calculada con los datos del periodo.",
    noMeasurements: "Sin mediciones en el periodo.",
    noChecks: "Sin controles en el periodo.",
    noInterventions: "Sin intervenciones en el periodo.",
    assistant: "Resumen asistido",
    assistantIntro:
      "Una lectura rápida del periodo y las acciones prioritarias.",
    generate: "Generar resumen IA",
    generating: "Analizando el periodo…",
    regenerate: "Actualizar resumen IA",
    automatic: "Resumen automático",
    ai: "Análisis IA · Hugging Face",
    highlights: "Puntos clave",
    recommendations: "Olivia AI recomienda",
    fallback:
      "El asistente IA no está disponible. El resumen automático sigue disponible.",
    notConfigured:
      "El resumen IA estará disponible cuando se configure el asistente. El resumen automático y las exportaciones ya están disponibles.",
    error: "La solicitud ha fallado. Inténtalo de nuevo en un momento.",
    rateLimited:
      "Demasiadas solicitudes en poco tiempo. Inténtalo de nuevo en un minuto.",
    generated: "Generado el",
    reviewNote:
      "El profesional debe revisar el resumen antes de compartirlo con el propietario.",
    loading: "Cargando…",
    scheduled: "Planificada",
    done: "Realizada",
    urgentStatus: "Urgente",
    type: "Tipo",
    status: "Estado",
    cover: "Cubierta",
    filtration: "Filtración",
    safety: "Seguridad",
    cleanliness: "Limpieza",
    passed: "OK",
    failed: "Por repetir",
    unknown: "Sin registrar",
    reportTitle: "Informe mensual de piscina",
    period: "Periodo",
    automaticPdf: "Resumen automático basado en los registros",
    estimated: "estimado",
    noPools: "No hay piscinas disponibles.",
  },
};
